# Imagem base Node.js
FROM node:18

# Define o diretório de trabalho
WORKDIR /app

# Copia o arquivo package.json para instalar as dependências
COPY package.json ./


# Instala as dependências
RUN npm install

# Copia o código do frontend
COPY ./src /app/src

# Compila o frontend
RUN npm run build

# Serve o frontend
RUN npm install -g serve
CMD ["serve", "-s", "dist"]

# Expõe a porta do frontend
EXPOSE 5000